workflow update

diff --git a/.github/workflows/Build-AMI-Packer.yml b/.github/workflows/Build-AMI-Packer.yml
--- a/.github/workflows/Build-AMI-Packer.yml
+++ b/.github/workflows/Build-AMI-Packer.yml
@@ -41,41 +41,44 @@ jobs:
           aws-access-key-id: ${{ secrets.DEMO_ACCESS }}
           aws-secret-access-key: ${{ secrets.DEMO_SECRET }}
           aws-region: ${{ secrets.AWS_REGION }}
-      - name: New Launch Template Version & ASG Refresh
+      - name: Update Launch Template
+        if: always()
         run: >
-          # Check if launch template ID and auto scaling group name are available
-
-          if ! [[ $launch_template_id == null ]] && ! [[ $auto_scaling_name == null ]]
-
-          then
-            echo "Launch Template Found"
-            # Create a new version of launch template
-            aws ec2 create-launch-template-version \
-              --launch-template-id $(aws ec2 describe-launch-templates \
-                                    --query 'sort_by(LaunchTemplates, &CreateTime)[-1].LaunchTemplateId' \
-                                    --output text) \
-              --version-description Version2 \
-              --source-version 1 \
-              --launch-template-data "ImageId=$(aws ec2 describe-images \
-                                                --owners ${{ secrets.AWS_DEV}} \
-                                                --query 'sort_by(Images, &CreationDate)[-1].ImageId' \
-                                                --output text)"
-            
-            # Start instance refresh for auto scaling group
-            aws autoscaling start-instance-refresh \
-              --auto-scaling-group-name $(aws autoscaling describe-auto-scaling-groups \
-                                          --query "AutoScalingGroups[0].AutoScalingGroupName" \
-                                          --output text)
-
-            
+          asg_name="webapp_autoscaling_group"
+          # Check if the autoscaling group exists
+          asg_exists=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $asg_name --query "length(AutoScalingGroups)")
+          if [ "$asg_exists" -eq 0 ]; then
+            echo "Autoscaling group $asg_name not found. Exiting."
+            exit 1
           else
-            echo "Launch Template Not Found"
-          fi
-
-
-          # Loop to check instance refresh status
-
-          while [[ "$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[0].AutoScalingGroupName" --output text) --query 'InstanceRefreshes[0].Status' --output text)" != "Successful" ]]; do
+            # Get the latest AMI ID
+            latest_ami=$(aws ec2 describe-images \
+            --owners self \
+            --filters "Name=state,Values=available" "Name=architecture,Values=x86_64" "Name=root-device-type,Values=ebs" \
+            --query "reverse(sort_by(Images, &CreationDate))[0].ImageId" \
+            )
+            echo "The latest AMI is: $latest_ami"
+            # Update the launch template with the latest AMI
+            aws ec2 create-launch-template-version \
+            --launch-template-name myLaunchTemplate \
+            --source-version 1 \
+            --launch-template-data '{"ImageId":'$latest_ami'}'
+            # Refresh instances in the autoscaling group
+            aws autoscaling start-instance-refresh \
+            --auto-scaling-group-name $asg_name
+            --preferences '{"InstanceWarmup": 300, "MinHealthyPercentage": 0, "InstanceRefreshType": "Replace"}' \
+            --query 'InstanceRefreshId')
+            echo "Instance Refresh ID: $refresh_output"
             echo "Waiting for instance refresh to complete..."
-            sleep 30
-          done
+            refresh_status=$(aws autoscaling describe-instance-refreshes \
+            --auto-scaling-group-name $asg_name \
+            --instance-refresh-ids $refresh_output \
+            --query 'InstanceRefreshes[0].Status')
+            echo "Instance Refresh Status: $refresh_status"
+            if [ "$refresh_status" = '"Successful"' ]; then
+              echo "Instance refresh successful."
+            else
+              echo "Instance refresh failed or is not yet successful."
+              exit 1
+            fi
+          fi
