initial commit

diff --git a/.github/workflows/npm-publish-github-packages.yml b/.github/workflows/npm-publish-github-packages.yml
--- a/.github/workflows/npm-publish-github-packages.yml
+++ b/.github/workflows/npm-publish-github-packages.yml
@@ -1,38 +1,56 @@
----
-name: test
+name: integration-test
 on:
   pull_request:
-    branches:
-      - main
-      - try1
-  pull_request_target:
-    branches:
-      - main
+    branches: [ main ]
 jobs:
-  build:
-    name: intergration
+  setup:
     runs-on: ubuntu-latest
-    services:
-      mysql:
-        image: mysql:5.7
-        env:
-          MYSQL_ALLOW_EMPTY_PASSWORD: yes
-          MYSQL_ROOT_HOST: "%"
-          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
-        ports:
-          - 3306:3306
-        options: --health-cmd="mysqladmin ping" --health-interval=10s
-          --health-timeout=5s --health-retries=5
     steps:
-      - name: testing
-        run: echo "Hello World!"
       - name: Checkout code
         uses: actions/checkout@v2
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: 14
+      - name: Create .env File
+        run: |
+          echo "PORT=3000" >> .env
+          echo "DB_HOST=127.0.0.1" >> .env
+          echo "DB_PORT=3306" >> .env
+          echo "DB_DATABASE=cloud_assignment" >> .env
+          echo "DB_USER=admin" >> .env
+          echo "DB_PASSWORD=admin@123" >> .env
+        working-directory: ${{ github.workspace }}
+      - name: Set up Node.js and npm
+        run: |
+          sudo apt update
+          sudo apt install -y nodejs npm
+        continue-on-error: true # Continue even if this step fails
+      - name: Set up MariaDB
+        run: |
+          sudo apt update
+          sudo apt install -y mariadb-server
+          sudo systemctl start mariadb
+          sudo systemctl enable mariadb
+          sudo mysqladmin -u root password "root"
+          sudo mysql -u root -p"root" -e "CREATE DATABASE cloud_assignment;"
+          sudo mysql -u root -p"root" -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin@123';"
+          sudo mysql -u root -p"root" -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;"
+          sudo mysql -u root -p"root" -e "FLUSH PRIVILEGES;"
+      - name: Display setup information
+        run: |
+          echo "Root password for MariaDB has been set to: root"
+          echo "Database cloud_assignment has been created."
+          echo "User admin with admin privileges has been created."
+          echo "Node.js, npm, and MariaDB have been installed."
       - name: Install dependencies
         run: npm install
-      - name: Test cases
-        run: npx jest
+      - name: Run index.js
+        run: node index.js &
+      - name: Wait for 10 seconds
+        run: sleep 10
+      - name: Check URL "http://localhost:3000/healthz"
+        run: |
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/healthz)
+          if [[ "$RESPONSE" -eq 200 ]]; then
+            echo "URL is accessible."
+          else
+            echo "URL returned a non-200 status code: $RESPONSE"
+            exit 1
+          fi
